Introduce types structure
krizoeris/Verthem pull request #11
Opened 2024-05-23 19:33 UTC by fillcrop

2024-05-24 05:49 UTC, krizoeris requested changes

2024-05-24 05:49 UTC, krizoeris commented on types/Campaign/Campaign.tsx
> +    _id: number;
remove _

2024-05-24 05:49 UTC, krizoeris commented
Fix unsuccessful vercel check

2024-05-27 18:28 UTC, krizoeris approved these changes

2024-05-28 04:13 UTC, rambaldoz approved these changes

2024-05-28 05:22 UTC, markvalenzuela72 approved these changes

2024-05-30 04:27 UTC, merged