Markvalenzuela72/ver 50
krizoeris/Verthem pull request #19
Opened 2024-06-05 16:46 UTC by markvalenzuela72

2024-06-08 15:51 UTC, mjdc commented on actions/userActions.ts
>  export async function createUserSSO(
@markvalenzuela72 , you can rename this to just createUser

2024-06-08 17:50 UTC, krizoeris requested changes

2024-06-08 17:50 UTC, krizoeris commented on lib/auth.config.ts
Prefer to create a 'auth' directory and insert this to 'auth.config.ts' and 'auth.ts' inside

2024-06-08 17:51 UTC, krizoeris commented
Fix the deployment issue: https://vercel.com/verthems-projects/verthem/2HSZZRMAD1YnKE1mHN2WHmaTzw8V

2024-06-09 10:52 UTC, krizoeris approved these changes

2024-06-10 06:01 UTC, merged